#!/bin/bash

warp-cli disconnect
sleep 1
warp-cli delete

sleep 1

warp-svc register& 
sudo systemctl enable --now warp-svc.service 
warp-cli register >/dev/null
warp-cli connect

sleep 2
echo ""
echo -n "currnet ip is : "
ifconfig -a | grep -E -o 'inet[[:space:]]([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'  | awk '{print $2; exit }' > ip.$$
currIP=$(<ip.$$);
rm ip.$$
echo $currIP

read -p "enter the path of open vpn file : " x


echo "
remove_me() {
    rm -- "\$0"
    exit
}
trap remove_me SIGINT


while ! ping -c 3 10.10.10.10; do
    sleep 0.5
    echo 'Trying to ping...'
    echo "press ctrl + c  to stop the program "
done

warp-cli disconnect
warp-cli delete
sleep 1
echo -n \"your ip now is : \"
ifconfig -a | grep -E -o 'inet[[:space:]]([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)' | awk 'END {print $2}'
rm \$0" > execute.$$



chmod u+x execute.$$

xdotool key ctrl+shift+t
xdotool type "bash execute.$$ "
xdotool key Return


sudo openvpn $x

