#!/bin/bash 
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <domains_file> <depth>"
    exit 1
fi

domains_file=$1
depth=$2

regex="^[^.]*"
for ((i=1; i<=$depth; i++)); do
    regex+="\.[^.]*"
done
regex+="$"


touch temp.$$ 
for domain in $(cat $domains_file)
do
    subfinder -d $domain | grep -E "$regex" | sort -u > temp.$$
           
    echo "number of subdomains of depth $depth of $domain is $(wc -l temp.$$ | cut -d " " -f1):- " >> final_subdomains.$$
    echo "----------------------------" >> final_subdomains.$$
    cat temp.$$ >> final_subdomains.$$

    echo " **************************************" >> final_subdomains.$$
    echo " **************************************" >> final_subdomains.$$
done

rm temp.$$ 

