#!/bin/bash

echo "hello this script use to generate a random password"

read -p "enter the length of the password : " len

while [[ !($len =~ ^[0-9]+$) ]]
do
    echo -n "$len is not a number... pleas enter a number : "
    read len

done

# this factors i will use to make the generated passwords  different
f1=$$  
f2=$(date +%Y%m%d%H%M%S)

chose()
{
    echo "you want password consist of :- "
    read -p " characters         ? [y/n] : " char
    read -p " numbers            ? [y/n] : " num
    read -p " special characters ? [y/n] : " speacialchar
}

char="n"
num="n"
speacialchar="n"

while [ 1 ]
do
    chose 
    if [[ $char == "y" || $num == "y" || $speacialchar == "y"  ]]
    then
    break
    fi
    echo ""
    echo "######  you must chose at least one  ########"
done

arr_char=()
arr_num=()
arr_special=()

if [ $char == "y" ]
then
    for i in {a..z}
    do
    arr_char+=("$i")  
    done

    for i in {A..Z}
    do
    arr_char+=("$i")  
    done
fi

if [ $num == "y" ]
then
    for i in {0..9}
    do
    arr_num+=("$i")  
    done
fi

if [ $speacialchar == "y" ]
then
    arr_special=("!" "@" "#" "$" "%" "^" "&" "*" "(" ")" "_" "+" )
fi

# echo "${arr[@]}"
pass=""
len1=${#arr_char[@]}
len2=${#arr_num[@]}
len3=${#arr_special[@]}


while [ $len -ne 0 ]
do
    ind=$(((f1 * f2) % 93894323))
    if [ $ind -lt 0 ]
    then
        ind=$((ind * -1))
    fi
    # echo "$f1  $f2"
    f1=$(((f1 * f2) % 43543537))
    f2=$(((f2 * f1) % 34753545))
   
##########################
    if [ $char == "y" ]
    then
    pass+=${arr_char[$((ind % len1))]}
    ((len--))
    fi

    if [ $len -eq 0 ]
    then
        break
    fi
#############################
    if [ $num == "y" ]
    then
    pass+=${arr_num[$((ind % len2))]}
    ((len--))
    fi

    if [ $len -eq 0 ]
    then
        break
    fi
##################################
    if [ $speacialchar == "y" ]
    then
    pass+=${arr_special[$((ind % len3))]}
    ((len--))
    fi

    if [ $len -eq 0 ]
    then
        break
    fi
done


echo pawssword is : $pass
